load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary")

cc_library(
    name = "pic",
    deps = [
        "//data/particle:particle",
        "//data/field:field",
        "//data/grid:grid",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [":pic"],
    copts = ["-std=c++20", "-O3", "-march=native"],
)
