load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "sorter",
    hdrs = [
        "particle_sorter.hpp",
    ],
    deps = [
        "//data/grid:grid",
        "//data/particle:particle",
    ],
    copts = [
        "-O3",                           # Triggers vectorization pipelines
        "-fopenmp-simd",                 # Parses OpenMP SIMD directives without full OpenMP runtime cost
    ],
    visibility = ["//visibility:public"],
)