load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "kernels",
    deps = [
        "//kernels/field",
        "//kernels/pusher",
        "//kernels/gather",
        "//kernels/shapes",
        "//kernels/deposit",
        "//kernels/sorter",
    ],
    visibility = ["//visibility:public"],
)