load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary")
load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

cc_library(
    name = "app_lib",
    hdrs = glob(["*.hpp"]),
    deps = [
        "//engine",
        "//kernels/shapes",
    ],
    include_prefix = "",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "ui_colors",
    hdrs = ["Colors.hpp"],
    include_prefix = "",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "ui_verification_report",
    hdrs = [
        "VerificationReport.hpp",
    ],
    deps = ["//app:ui_colors"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "app_bin",
    srcs = ["app.cpp"],
    deps = [
        ":app_lib",
        "//engine",
    ],
    visibility = ["//visibility:public"],
)

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = [":app_bin"],
)