load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary")

cc_library(
    name = "app_lib",
    hdrs = glob(["*.hpp"]),
    deps = ["//engine"],
    include_prefix = "",
    copts = ["-O3", "-march=native"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "app_bin",
    srcs = ["app.cpp"],
    deps = [
        ":app_lib",
        "//engine",
    ],
    copts = ["-O3", "-march=native", "-std=c++20"],
    visibility = ["//visibility:public"],
)
