load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "pusher",
    hdrs = [
        "boris.hpp",
        "relativistic_boris.hpp",
    ],
    deps = [
        "@openmp//:openmp",
        "//data/field:field",
        "//data/particle:particle",
    ],
    visibility = ["//visibility:public"],
)