load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "deposit",
    hdrs = ["deposit.hpp"],
    deps = [
        "//data/field:field",
        "//data/grid:grid",
        "//data/particle:particle",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "esirkepov",
    hdrs = ["esirkepov.hpp"],
    deps = [
        "//data/field:field",
        "//data/grid:grid",
        "//data/particle:particle",
    ],
    visibility = ["//visibility:public"],
)