load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "operators",
    hdrs = glob(["include/*.hpp", "src/*.inl"]),
    deps = [
        "//grid:grid",
        "//field:field",
        "//particle:particle"
    ],
    includes = ["include"],
    include_prefix = "",
    copts = ["-O3", "-march=native"],
    visibility = ["//visibility:public"],
)
