load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "plasma_oscillation",
    srcs = ["plasma_oscillation.cpp"],
    copts = ["-std=c++20", "-faligned-allocation", "-O3", "-march=native"],
    deps = [
        "//app:app_lib",
        "//engine",
    ],
)

cc_binary(
    name = "energy_conservation",
    srcs = ["energy_conservation.cpp"],
    copts = ["-std=c++20", "-faligned-allocation", "-O3", "-march=native"],
    deps = [
        "//app:app_lib",
        "//engine",
    ],
)